window.NBV_VOICE = {
  locale: { en:"en-IN", ta:"ta-IN", te:"te-IN", hi:"hi-IN", ml:"ml-IN" },
  ui: {
    en:{title:"🎤 Ask Namma Bharat Vault",subtitle:"Speak your question and get simple financial safety guidance.",start:"Start listening",stop:"Stop listening",questionLabel:"Type a question",questionPlaceholder:"For example: What is OTP?",ask:"Ask",responseTitle:"Safety guidance",initialResponse:"Your answer will appear here.",speak:"Speak response",supportNote:"Speech recognition support and offline behavior depend on your browser. You can type a question instead.",listening:"Listening… speak now.",stopped:"Listening stopped.",unsupported:"Voice input is not supported in this browser. You can type your question instead.",speechUnavailable:"Speech output is not supported in this browser.",recognitionError:"Voice input could not be completed. You can type your question instead.",noSpeech:"No speech was detected. Please try again or type your question.",youSaid:"You said:",unknown:"I can help with scanning, OTP, UPI PIN, suspicious messages, and reporting lost money. Try asking one of those questions."},
    ta:{title:"🎤 நம்ம பாரத் வால்ட்டிடம் கேளுங்கள்",subtitle:"உங்கள் கேள்வியைச் சொல்லுங்கள்; எளிய நிதி பாதுகாப்பு ஆலோசனையைப் பெறுங்கள்.",start:"கேட்கத் தொடங்கு",stop:"கேட்பதை நிறுத்து",questionLabel:"உங்கள் கேள்வியை எழுதுங்கள்",questionPlaceholder:"உதாரணம்: OTP என்றால் என்ன?",ask:"கேள்",responseTitle:"பாதுகாப்பு ஆலோசனை",initialResponse:"உங்கள் பதில் இங்கே காட்டப்படும்.",speak:"பதிலைக் கேளுங்கள்",supportNote:"குரல் வசதியும் இணையமின்றி செயல்படுவதும் உலாவியைப் பொறுத்தது. கேள்வியை எழுதவும் முடியும்.",listening:"கேட்கிறது… இப்போது பேசுங்கள்.",stopped:"கேட்பது நிறுத்தப்பட்டது.",unsupported:"இந்த உலாவியில் குரல் உள்ளீடு இல்லை. உங்கள் கேள்வியை எழுதலாம்.",speechUnavailable:"இந்த உலாவியில் குரல் பதில் வசதி இல்லை.",recognitionError:"குரல் உள்ளீட்டை முடிக்க முடியவில்லை. உங்கள் கேள்வியை எழுதலாம்.",noSpeech:"குரல் கேட்கப்படவில்லை. மீண்டும் முயற்சிக்கவும் அல்லது கேள்வியை எழுதவும்.",youSaid:"நீங்கள் சொன்னது:",unknown:"செய்தி சரிபார்ப்பு, OTP, UPI PIN, சந்தேகச் செய்திகள், பண இழப்பு குறித்து கேளுங்கள்."},
    te:{title:"🎤 నమ్మ భారత్ వాల్ట్‌ను అడగండి",subtitle:"మీ ప్రశ్న చెప్పండి; సులభమైన ఆర్థిక భద్రత సూచనలు పొందండి.",start:"వినడం ప్రారంభించండి",stop:"వినడం ఆపండి",questionLabel:"మీ ప్రశ్న టైప్ చేయండి",questionPlaceholder:"ఉదాహరణ: OTP అంటే ఏమిటి?",ask:"అడగండి",responseTitle:"భద్రత సూచనలు",initialResponse:"మీ సమాధానం ఇక్కడ కనిపిస్తుంది.",speak:"సమాధానం వినండి",supportNote:"వాయిస్ గుర్తింపు, ఆఫ్‌లైన్‌లో దాని పని బ్రౌజర్‌పై ఆధారపడి ఉంటాయి. మీరు ప్రశ్న టైప్ చేయవచ్చు.",listening:"వింటోంది… ఇప్పుడు మాట్లాడండి.",stopped:"వినడం ఆగింది.",unsupported:"ఈ బ్రౌజర్‌లో వాయిస్ ఇన్‌పుట్ లేదు. మీ ప్రశ్నను టైప్ చేయవచ్చు.",speechUnavailable:"ఈ బ్రౌజర్‌లో వాయిస్ అవుట్‌పుట్ లేదు.",recognitionError:"వాయిస్ ఇన్‌పుట్ పూర్తి కాలేదు. మీ ప్రశ్నను టైప్ చేయవచ్చు.",noSpeech:"మాట వినిపించలేదు. మళ్లీ ప్రయత్నించండి లేదా టైప్ చేయండి.",youSaid:"మీరు చెప్పింది:",unknown:"సందేశ తనిఖీ, OTP, UPI PIN, అనుమానాస్పద సందేశాలు లేదా పోయిన డబ్బు గురించి అడగండి."},
    hi:{title:"🎤 नम्मा भारत वॉल्ट से पूछें",subtitle:"अपना सवाल बोलें और सरल वित्तीय सुरक्षा सलाह पाएँ।",start:"सुनना शुरू करें",stop:"सुनना बंद करें",questionLabel:"अपना सवाल लिखें",questionPlaceholder:"उदाहरण: OTP क्या है?",ask:"पूछें",responseTitle:"सुरक्षा सलाह",initialResponse:"आपका जवाब यहाँ दिखाई देगा।",speak:"जवाब सुनें",supportNote:"आवाज़ पहचान और उसका ऑफ़लाइन काम ब्राउज़र पर निर्भर करता है। आप सवाल लिख भी सकते हैं।",listening:"सुन रहा है… अब बोलें।",stopped:"सुनना बंद हुआ।",unsupported:"इस ब्राउज़र में आवाज़ इनपुट उपलब्ध नहीं है। आप सवाल लिख सकते हैं।",speechUnavailable:"इस ब्राउज़र में आवाज़ में जवाब उपलब्ध नहीं है।",recognitionError:"आवाज़ इनपुट पूरा नहीं हो सका। आप सवाल लिख सकते हैं।",noSpeech:"आवाज़ नहीं मिली। फिर कोशिश करें या सवाल लिखें।",youSaid:"आपने कहा:",unknown:"संदेश जाँच, OTP, UPI PIN, संदिग्ध संदेश या खोए पैसे के बारे में पूछें।"},
    ml:{title:"🎤 നമ്മ ഭാരത് വോൾട്ടിനോട് ചോദിക്കൂ",subtitle:"നിങ്ങളുടെ ചോദ്യം പറയൂ; ലളിതമായ സാമ്പത്തിക സുരക്ഷാ ഉപദേശം നേടൂ.",start:"കേൾക്കാൻ തുടങ്ങുക",stop:"കേൾക്കുന്നത് നിർത്തുക",questionLabel:"ചോദ്യം ടൈപ്പ് ചെയ്യുക",questionPlaceholder:"ഉദാഹരണം: OTP എന്താണ്?",ask:"ചോദിക്കുക",responseTitle:"സുരക്ഷാ ഉപദേശം",initialResponse:"നിങ്ങളുടെ ഉത്തരം ഇവിടെ കാണിക്കും.",speak:"ഉത്തരം കേൾക്കുക",supportNote:"ശബ്ദ തിരിച്ചറിയലും ഓഫ്‌ലൈൻ പ്രവർത്തനവും ബ്രൗസറിനെ ആശ്രയിച്ചിരിക്കുന്നു. ചോദ്യം ടൈപ്പ് ചെയ്യാം.",listening:"കേൾക്കുന്നു… ഇപ്പോൾ സംസാരിക്കുക.",stopped:"കേൾക്കുന്നത് നിർത്തി.",unsupported:"ഈ ബ്രൗസറിൽ ശബ്ദ ഇൻപുട്ട് ലഭ്യമല്ല. ചോദ്യം ടൈപ്പ് ചെയ്യാം.",speechUnavailable:"ഈ ബ്രൗസറിൽ ശബ്ദ മറുപടി ലഭ്യമല്ല.",recognitionError:"ശബ്ദ ഇൻപുട്ട് പൂർത്തിയാക്കാനായില്ല. ചോദ്യം ടൈപ്പ് ചെയ്യാം.",noSpeech:"സംസാരം കണ്ടെത്തിയില്ല. വീണ്ടും ശ്രമിക്കുകയോ ടൈപ്പ് ചെയ്യുകയോ ചെയ്യുക.",youSaid:"നിങ്ങൾ പറഞ്ഞത്:",unknown:"സന്ദേശ പരിശോധന, OTP, UPI PIN, സംശയമുള്ള സന്ദേശങ്ങൾ, നഷ്ടപ്പെട്ട പണം എന്നിവ ചോദിക്കാം."}
  },
  response: {
    en:{home:"Opening Home.",scanner:"Opening the Message Scanner. Paste or speak the message, then choose Scan message.",guide:"Opening the Safety Guide.",otpWhat:"An OTP is a one-time password used to verify an action. Never share it with anyone, including someone claiming to be from your bank.",otpShare:"No. Never share your OTP with anyone. Banks do not need you to tell them your OTP.",upiWhat:"Your UPI PIN is the private PIN you use to authorize sending money.",upiShare:"No. Keep your UPI PIN private. You do not need to share it to receive money.",scanHow:"Open the Scanner, paste the message, and select Scan message. The check runs locally using the existing rules.",lost:"If you lost money to a scam, contact your bank and call the cyber-crime helpline 1930 as soon as possible.",noCurrent:"Please scan a message first, then I can explain its risk.",current:"This message is currently marked {level} risk with a score of {score} out of 100. Warning signs: {reasons}",currentClear:"This message is currently marked {level} risk with a score of {score} out of 100. No known warning signs were found; stay alert.",unknown:"I can help with scanning, OTP, UPI PIN, suspicious messages, and lost money. Try asking one of those questions."},
    ta:{home:"முகப்புப் பக்கத்தைத் திறக்கிறேன்.",scanner:"செய்தி சரிபார்ப்பைத் திறக்கிறேன். செய்தியை ஒட்டி அல்லது சொல்லி, பின்னர் சரிபார்க்கவும்.",guide:"பாதுகாப்பு வழிகாட்டியைத் திறக்கிறேன்.",otpWhat:"OTP என்பது ஒரு முறை பயன்படுத்தும் கடவுச்சொல். வங்கி என்று கூறுபவரிடமும் யாரிடமும் இதைப் பகிராதீர்கள்.",otpShare:"வேண்டாம். OTP-ஐ யாரிடமும் பகிராதீர்கள். வங்கிக்கு அதைச் சொல்ல வேண்டியதில்லை.",upiWhat:"பணம் அனுப்புவதை உறுதிப்படுத்தப் பயன்படுத்தும் தனிப்பட்ட PIN தான் UPI PIN.",upiShare:"வேண்டாம். UPI PIN தனிப்பட்டது. பணம் பெற அதைப் பகிரத் தேவையில்லை.",scanHow:"செய்தி சரிபார்ப்பைத் திறந்து செய்தியை ஒட்டி, சரிபார்க்கவும் என்பதைத் தேர்ந்தெடுக்கவும். ஆய்வு உள்ளூரில் நடக்கும்.",lost:"மோசடியில் பணம் இழந்தால் உங்கள் வங்கியைத் தொடர்புகொண்டு இணையக் குற்ற உதவி எண் 1930-ஐ உடனே அழைக்கவும்.",noCurrent:"முதலில் ஒரு செய்தியைச் சரிபார்க்கவும்; அதன் ஆபத்தை நான் விளக்குகிறேன்.",current:"இந்தச் செய்தி தற்போது {level} ஆபத்து எனக் குறிக்கப்பட்டுள்ளது; மதிப்பெண் {score}/100. எச்சரிக்கை அறிகுறிகள்: {reasons}",currentClear:"இந்தச் செய்தி தற்போது {level} ஆபத்து எனக் குறிக்கப்பட்டுள்ளது; மதிப்பெண் {score}/100. அறியப்பட்ட எச்சரிக்கை அறிகுறிகள் இல்லை; விழிப்புடன் இருங்கள்.",unknown:"செய்தி சரிபார்ப்பு, OTP, UPI PIN, சந்தேகச் செய்திகள் மற்றும் பண இழப்பு பற்றி கேளுங்கள்."},
    te:{home:"హోమ్ తెరుస్తున్నాను.",scanner:"సందేశ స్కానర్ తెరుస్తున్నాను. సందేశాన్ని అతికించి లేదా చెప్పి, స్కాన్ చేయండి.",guide:"భద్రత మార్గదర్శిని తెరుస్తున్నాను.",otpWhat:"OTP అనేది ఒకసారి ఉపయోగించే పాస్‌వర్డ్. బ్యాంకు అని చెప్పుకునే వారితో సహా ఎవరితోనూ పంచుకోవద్దు.",otpShare:"వద్దు. మీ OTPని ఎవరితోనూ పంచుకోవద్దు. బ్యాంకుకు కూడా మీరు OTP చెప్పాల్సిన అవసరం లేదు.",upiWhat:"డబ్బు పంపడాన్ని ఆమోదించడానికి ఉపయోగించే ప్రైవేట్ PIN మీ UPI PIN.",upiShare:"వద్దు. మీ UPI PINను రహస్యంగా ఉంచండి. డబ్బు స్వీకరించడానికి దాన్ని పంచుకోవాల్సిన అవసరం లేదు.",scanHow:"సందేశ స్కానర్ తెరిచి సందేశాన్ని అతికించి, స్కాన్ చేయండి. ఈ తనిఖీ స్థానిక నియమాలతో జరుగుతుంది.",lost:"మోసంలో డబ్బు పోతే, మీ బ్యాంకును సంప్రదించి సైబర్ క్రైమ్ హెల్ప్‌లైన్ 1930కు వెంటనే కాల్ చేయండి.",noCurrent:"ముందుగా ఒక సందేశాన్ని స్కాన్ చేయండి; తర్వాత దాని ప్రమాదాన్ని వివరిస్తాను.",current:"ఈ సందేశం ప్రస్తుతం {level} ప్రమాదంగా గుర్తించబడింది; స్కోరు {score}/100. హెచ్చరికలు: {reasons}",currentClear:"ఈ సందేశం ప్రస్తుతం {level} ప్రమాదంగా గుర్తించబడింది; స్కోరు {score}/100. తెలిసిన హెచ్చరికలు లేవు; అప్రమత్తంగా ఉండండి.",unknown:"సందేశ స్కాన్, OTP, UPI PIN, అనుమానాస్పద సందేశాలు లేదా డబ్బు పోవడం గురించి అడగండి."},
    hi:{home:"होम खोल रहा हूँ।",scanner:"संदेश स्कैनर खोल रहा हूँ। संदेश डालें या बोलें, फिर स्कैन करें।",guide:"सुरक्षा मार्गदर्शिका खोल रहा हूँ।",otpWhat:"OTP एक बार इस्तेमाल होने वाला पासवर्ड है। बैंक का दावा करने वाले व्यक्ति सहित किसी से साझा न करें।",otpShare:"नहीं। अपना OTP किसी से साझा न करें। बैंक को भी आपको OTP बताने की ज़रूरत नहीं होती।",upiWhat:"UPI PIN वह निजी PIN है जिससे पैसे भेजने की पुष्टि होती है।",upiShare:"नहीं। अपना UPI PIN गोपनीय रखें। पैसे पाने के लिए इसे साझा करने की ज़रूरत नहीं।",scanHow:"संदेश स्कैनर खोलें, संदेश डालें और स्कैन करें चुनें। जाँच मौजूदा नियमों से इसी डिवाइस पर होती है।",lost:"धोखाधड़ी में पैसे खोने पर अपने बैंक से संपर्क करें और साइबर अपराध हेल्पलाइन 1930 पर जल्द कॉल करें।",noCurrent:"पहले कोई संदेश स्कैन करें, फिर मैं उसका जोखिम समझा सकता हूँ।",current:"यह संदेश अभी {level} जोखिम के रूप में चिह्नित है; स्कोर {score}/100 है। चेतावनी संकेत: {reasons}",currentClear:"यह संदेश अभी {level} जोखिम के रूप में चिह्नित है; स्कोर {score}/100 है। कोई ज्ञात चेतावनी संकेत नहीं मिला; सतर्क रहें।",unknown:"संदेश स्कैन, OTP, UPI PIN, संदिग्ध संदेश और खोए पैसे के बारे में पूछें।"},
    ml:{home:"ഹോം തുറക്കുന്നു.",scanner:"സന്ദേശ പരിശോധന തുറക്കുന്നു. സന്ദേശം ചേർക്കുകയോ പറയുകയോ ചെയ്ത് സ്കാൻ ചെയ്യുക.",guide:"സുരക്ഷാ മാർഗ്ഗനിർദ്ദേശം തുറക്കുന്നു.",otpWhat:"OTP ഒരിക്കൽ ഉപയോഗിക്കുന്ന പാസ്‌വേഡാണ്. ബാങ്കിൽ നിന്നാണെന്ന് പറയുന്നവരോടുൾപ്പെടെ ആരുമായും പങ്കിടരുത്.",otpShare:"വേണ്ട. OTP ആരുമായും പങ്കിടരുത്. ബാങ്കിനും നിങ്ങളോട് OTP പറയേണ്ടതില്ല.",upiWhat:"പണം അയയ്ക്കുന്നത് അംഗീകരിക്കാൻ ഉപയോഗിക്കുന്ന സ്വകാര്യ PIN ആണ് UPI PIN.",upiShare:"വേണ്ട. UPI PIN സ്വകാര്യമായി സൂക്ഷിക്കുക. പണം സ്വീകരിക്കാൻ അത് പങ്കിടേണ്ടതില്ല.",scanHow:"സന്ദേശ പരിശോധന തുറന്ന് സന്ദേശം ചേർത്ത് സ്കാൻ ചെയ്യുക. നിലവിലുള്ള നിയമങ്ങൾ ഉപയോഗിച്ച് പരിശോധന ഉപകരണത്തിൽ തന്നെ നടക്കും.",lost:"തട്ടിപ്പിൽ പണം നഷ്ടപ്പെട്ടാൽ ബാങ്കുമായി ബന്ധപ്പെടുകയും സൈബർ ക്രൈം ഹെൽപ്‌ലൈൻ 1930-ൽ ഉടൻ വിളിക്കുകയും ചെയ്യുക.",noCurrent:"ആദ്യം ഒരു സന്ദേശം സ്കാൻ ചെയ്യൂ; അതിന്റെ അപകടം ഞാൻ വിശദീകരിക്കാം.",current:"ഈ സന്ദേശം ഇപ്പോൾ {level} അപകടമായി അടയാളപ്പെടുത്തിയിരിക്കുന്നു; സ്കോർ {score}/100. മുന്നറിയിപ്പുകൾ: {reasons}",currentClear:"ഈ സന്ദേശം ഇപ്പോൾ {level} അപകടമായി അടയാളപ്പെടുത്തിയിരിക്കുന്നു; സ്കോർ {score}/100. അറിയപ്പെടുന്ന മുന്നറിയിപ്പുകളില്ല; ജാഗ്രത പാലിക്കുക.",unknown:"സന്ദേശ പരിശോധന, OTP, UPI PIN, സംശയമുള്ള സന്ദേശങ്ങൾ, നഷ്ടപ്പെട്ട പണം എന്നിവ ചോദിക്കാം."}
  }
};

window.NBV_VOICE.guidanceLead = {
  en:" Safety steps: ",
  ta:" செய்ய வேண்டியது: ",
  te:" చేయాల్సినవి: ",
  hi:" आगे क्या करें: ",
  ml:" ചെയ്യേണ്ടത്: "
};

window.NBV_VOICE.intents = {
  en: {
    currentScan:[/\b(?:is|was)\s+(?:this|the)\s+(?:message|sms)\s+(?:safe|suspicious|risky)\b/i,/\bwhy\b.{0,40}\b(?:message|sms|this)\b.{0,30}\b(?:suspicious|risky|flagged)\b/i,/\bwhat(?:\s+is|'s)\s+(?:the\s+)?risk\b/i,/\b(?:message|sms)\b.{0,30}\b(?:risk|suspicious|risky)\b/i],
    lostMoney:[/\b(?:lost|lose|losing)\s+(?:my\s+)?(?:money|funds)\b/i,/\b(?:money|funds)\s+(?:(?:was|were|has been|have been)\s+)?(?:stolen|taken|lost)\b/i,/\b(?:got|been|was)\s+scammed\b/i,/\b(?:sent|transferred)\s+(?:money|funds)\b.{0,50}\bscammer?\b/i,/\b(?:report|reporting)\s+(?:a\s+)?(?:financial\s+)?fraud\b/i,/\bhow\b.{0,30}\breport\b.{0,25}\bfraud\b/i,/\bwhat\s+should\s+i\s+do\b.{0,40}\b(?:fraud|scam|stolen)\b/i],
    upiPin:[/\bupi\s*pin\b/i],
    otp:[/\botp\b|\bone[ -]?time\s+password\b/i],
    scanner:[/\b(?:open|show|go to|take me to)\s+(?:the\s+)?(?:message\s+)?scanner\b/i,/\b(?:scan|check)\s+(?:this|the|a)?\s*(?:suspicious\s*)?(?:message|sms)\b/i,/\bhow\b.{0,35}\b(?:scan|check)\b.{0,30}\b(?:message|sms)\b/i,/\bi\s+want\s+to\s+check\b.{0,35}\b(?:message|sms)\b/i],
    safetyGuide:[/\b(?:open|show|go to|take me to)\s+(?:the\s+)?(?:safety\s+)?guide\b/i,/\b(?:give|show)\s+me\b.{0,20}\bsafety\s+tips\b/i,/\bhow\b.{0,30}\bstay\s+safe\b.{0,30}\b(?:online\s+)?(?:scams?|fraud)\b/i],
    home:[/\b(?:go|take me)\s+to\s+home\b/i,/\bopen\s+home\b/i,/\bgo\s+home\b/i]
  },
  ta: {
    currentScan:[/இந்த\s*(?:செய்தி|sms).*(?:பாதுகாப்பா|ஆபத்து|சந்தேக)/u,/இந்த.*செய்தி.*ஏன்.*சந்தேக/u],lostMoney:[/பண.{0,30}(?:இழந்த|இழப்பு|திருட|மோசடி)/u,/மோசடி.{0,25}பண/u,/புகார்.{0,25}மோசடி/u],upiPin:[/upi\s*pin/i],otp:[/\botp\b/i],scanner:[/ஸ்கேனர்|ஸ்கேன்|சரிபார்க்க.{0,25}(?:செய்தி|sms)/u,/செய்தி.{0,25}(?:ஸ்கேன்|சரிபார்க்க)/u],safetyGuide:[/பாதுகாப்பு\s*வழிகாட்டி|பாதுகாப்பு\s*குறிப்புகள்/u],home:[/முகப்பு/u]
  },
  te: {
    currentScan:[/ఈ\s*(?:సందేశం|sms).*(?:సురక్షితమా|ప్రమాదం|అనుమానాస్పదం)/u,/ఈ.*సందేశం.*ఎందుకు.*అనుమాన/u],lostMoney:[/డబ్బు.{0,30}(?:పోయ|కోల్పోయ|దొంగతనం|మోస)/u,/మోస.{0,30}డబ్బు/u,/ఫిర్యాదు.{0,25}(?:మోస|డబ్బు)/u],upiPin:[/upi\s*pin/i],otp:[/\botp\b/i],scanner:[/స్కానర్|స్కాన్|తనిఖీ.{0,25}(?:సందేశ|sms)/u,/సందేశం.{0,25}(?:స్కాన్|తనిఖీ)/u],safetyGuide:[/భద్రత.{0,20}(?:మార్గదర్శి|చిట్కాలు)|సురక్షితంగా.{0,25}(?:మోస|స్కామ్)/u],home:[/హోమ్/u]
  },
  hi: {
    currentScan:[/इस\s+(?:संदेश|sms).*(?:सुरक्षित|जोखिम|संदिग्ध)/u,/यह.*संदेश.*क्यों.*संदिग्ध/u],lostMoney:[/पैस.{0,30}(?:खो|चोरी|धोख|गए)|धोखाधड़ी|फ्रॉड|स्कैम|रिपोर्ट.{0,20}धोख/u],upiPin:[/upi\s*pin/i],otp:[/\botp\b/i],scanner:[/स्कैनर|स्कैन|जाँच.{0,25}(?:संदेश|sms)/u,/संदेश.{0,25}(?:स्कैन|जाँच)/u],safetyGuide:[/सुरक्षा.{0,20}(?:मार्गदर्शिका|सुझाव|टिप्स)|सुरक्षित.{0,25}(?:स्कैम|धोख)/u],home:[/होम/u]
  },
  ml: {
    currentScan:[/ഈ\s*(?:സന്ദേശം|sms).*(?:സുരക്ഷിതമാണോ|അപകടം|സംശയ)/u,/ഈ.*സന്ദേശം.*എന്തുകൊണ്ട്.*സംശയ/u],lostMoney:[/പണം.{0,30}(?:നഷ്ട|മോഷ്ട|തട്ടിപ്പ്)/u,/തട്ടിപ്പ്.{0,30}പണം/u,/റിപ്പോർട്ട്.{0,25}തട്ടിപ്പ്/u],upiPin:[/upi\s*pin/i],otp:[/\botp\b/i],scanner:[/സ്കാനർ|സ്കാൻ|പരിശോധി.{0,25}(?:സന്ദേശ|sms)/u,/സന്ദേശം.{0,25}(?:സ്കാൻ|പരിശോധി)/u],safetyGuide:[/സുരക്ഷാ\s*(?:മാർഗ്ഗനിർദ്ദേശം|നിർദ്ദേശം|ഉപദേശം)|സുരക്ഷിത.{0,25}(?:തട്ടിപ്പ്|സ്കാം)/u],home:[/ഹോം/u]
  }
};

window.NBV_VOICE.answers = {
  en:{otp:"OTP means One-Time Password. It is a temporary verification code used once. Never share it with anyone; a genuine bank or support person should not ask you to disclose it.",upiPin:"No. Your UPI PIN is private. Never share it or enter it because someone asks through a call, message, or link. You do not need a UPI PIN to receive money.",lostMoney:"If you lost money or were scammed, contact your bank and call India's cyber-crime helpline 1930 as soon as possible. Do not share your OTP or UPI PIN with anyone.",scanner:"Open the Message Scanner, paste or type the SMS, then choose Scan message. The existing rule-based check runs locally and shows a score, warning signs, and safety guidance.",safetyGuide:"To stay safer: never share OTPs or UPI PINs; avoid suspicious links; verify messages through official bank channels; and do not rush because a message creates urgency. If money is lost, contact your bank and call 1930.",noCurrent:"Please scan a message first. Then I can explain its risk level and warning signs.",current:"This message is currently marked {level} RISK with a score of {score}/100. The scanner detected: {reasons}. {safety}",currentClear:"This message is currently marked {level} risk with a score of {score}/100. The scanner found no known warning signs. Stay alert. {safety}",currentSafety:"Do not click suspicious links or share OTP/PIN. Verify through official bank channels and do not rush."},
  ta:{otp:"OTP என்றால் One-Time Password, அதாவது ஒருமுறை பயன்படுத்தும் தற்காலிக சரிபார்ப்புக் குறியீடு. அதை யாரிடமும் பகிராதீர்கள்; உண்மையான வங்கி அல்லது உதவி நபர் OTP-ஐக் கேட்கக் கூடாது.",upiPin:"வேண்டாம். UPI PIN தனிப்பட்டது. அழைப்பு, செய்தி அல்லது இணைப்பில் யாராவது கேட்டாலும் பகிரவோ உள்ளிடவோ வேண்டாம். பணம் பெற UPI PIN தேவையில்லை.",lostMoney:"பணம் இழந்தாலோ மோசடிக்கு ஆளானாலோ உடனே உங்கள் வங்கியைத் தொடர்புகொண்டு இணையக் குற்ற உதவி எண் 1930-ஐ அழைக்கவும். OTP அல்லது UPI PIN-ஐ யாரிடமும் பகிராதீர்கள்.",scanner:"செய்தி சரிபார்ப்பைத் திறந்து SMS-ஐ ஒட்டவும் அல்லது எழுதவும்; பின்னர் சரிபார்க்கவும் என்பதைத் தேர்ந்தெடுக்கவும். உள்ளூர் விதி ஆய்வு மதிப்பெண், எச்சரிக்கை அறிகுறிகள், ஆலோசனை ஆகியவற்றைக் காட்டும்.",safetyGuide:"பாதுகாப்பாக இருக்க: OTP அல்லது UPI PIN-ஐ பகிராதீர்கள்; சந்தேக இணைப்புகளைத் திறக்காதீர்கள்; வங்கியின் அதிகாரப்பூர்வ வழியில் சரிபார்க்கவும்; அவசரப்படுத்தும் செய்தியை நம்பி செயல்படாதீர்கள். பணம் இழந்தால் வங்கியையும் 1930-ஐயும் தொடர்புகொள்ளுங்கள்.",noCurrent:"முதலில் ஒரு செய்தியைச் சரிபார்க்கவும். அதன் ஆபத்து நிலையும் காரணங்களையும் பின்னர் விளக்குகிறேன்.",current:"இந்தச் செய்தி தற்போது {level} ஆபத்து எனக் குறிக்கப்பட்டுள்ளது; மதிப்பெண் {score}/100. கண்டறியப்பட்டவை: {reasons}. {safety}",currentClear:"இந்தச் செய்தி தற்போது {level} ஆபத்து; மதிப்பெண் {score}/100. அறியப்பட்ட எச்சரிக்கை அறிகுறிகள் இல்லை. விழிப்புடன் இருங்கள். {safety}",currentSafety:"சந்தேக இணைப்புகளைத் திறக்காதீர்கள்; OTP/PIN பகிராதீர்கள். வங்கியின் அதிகாரப்பூர்வ வழியில் சரிபார்த்து, அவசரப்படாதீர்கள்."},
  te:{otp:"OTP అంటే One-Time Password, ఒకసారి ఉపయోగించే తాత్కాలిక ధృవీకరణ కోడ్. దాన్ని ఎవరితోనూ పంచుకోవద్దు; నిజమైన బ్యాంకు లేదా సహాయకుడు OTP అడగకూడదు.",upiPin:"వద్దు. UPI PIN వ్యక్తిగతమైనది. కాల్, సందేశం లేదా లింక్ ద్వారా ఎవరైనా అడిగినా పంచుకోవద్దు లేదా నమోదు చేయవద్దు. డబ్బు స్వీకరించడానికి UPI PIN అవసరం లేదు.",lostMoney:"డబ్బు పోయినా లేదా మోసానికి గురైనా వెంటనే మీ బ్యాంకును సంప్రదించి సైబర్ క్రైమ్ హెల్ప్‌లైన్ 1930కు కాల్ చేయండి. OTP లేదా UPI PINను ఎవరితోనూ పంచుకోవద్దు.",scanner:"సందేశ స్కానర్ తెరిచి SMSను అతికించండి లేదా టైప్ చేయండి; తర్వాత స్కాన్ చేయండి. స్థానిక నియమాల తనిఖీ స్కోరు, హెచ్చరికలు, భద్రత సూచనలు చూపుతుంది.",safetyGuide:"సురక్షితంగా ఉండటానికి OTP లేదా UPI PINను పంచుకోవద్దు; అనుమానాస్పద లింక్‌లు తెరవవద్దు; అధికారిక బ్యాంకు మార్గాల్లో ధృవీకరించండి; తొందరపడవద్దు. డబ్బు పోతే బ్యాంకును, 1930ను సంప్రదించండి.",noCurrent:"ముందుగా సందేశాన్ని స్కాన్ చేయండి. ఆ తర్వాత దాని ప్రమాద స్థాయి, హెచ్చరికలను వివరిస్తాను.",current:"ఈ సందేశం ప్రస్తుతం {level} ప్రమాదంగా గుర్తించబడింది; స్కోరు {score}/100. స్కానర్ గుర్తించినవి: {reasons}. {safety}",currentClear:"ఈ సందేశం ప్రస్తుతం {level} ప్రమాదం; స్కోరు {score}/100. తెలిసిన హెచ్చరికలు కనిపించలేదు. అప్రమత్తంగా ఉండండి. {safety}",currentSafety:"అనుమానాస్పద లింక్‌లు తెరవవద్దు; OTP/PIN పంచుకోవద్దు. అధికారిక బ్యాంకు మార్గాల్లో తనిఖీ చేసి, తొందరపడవద్దు."},
  hi:{otp:"OTP का अर्थ One-Time Password है। यह एक बार इस्तेमाल होने वाला अस्थायी सत्यापन कोड है। इसे किसी से साझा न करें; बैंक या सहायता कर्मी को आपसे OTP नहीं माँगना चाहिए।",upiPin:"नहीं। UPI PIN निजी है। कॉल, संदेश या लिंक पर किसी के कहने से इसे साझा या दर्ज न करें। पैसे पाने के लिए UPI PIN की ज़रूरत नहीं होती।",lostMoney:"पैसे खोने या धोखाधड़ी होने पर तुरंत अपने बैंक से संपर्क करें और साइबर अपराध हेल्पलाइन 1930 पर कॉल करें। OTP या UPI PIN किसी से साझा न करें।",scanner:"संदेश स्कैनर खोलें, SMS चिपकाएँ या लिखें, फिर स्कैन करें चुनें। स्थानीय नियमों की जाँच स्कोर, चेतावनी संकेत और सुरक्षा सलाह दिखाती है।",safetyGuide:"सुरक्षित रहने के लिए OTP या UPI PIN साझा न करें; संदिग्ध लिंक न खोलें; बैंक के आधिकारिक माध्यम से पुष्टि करें; जल्दबाज़ी न करें। पैसे खोने पर बैंक और 1930 से संपर्क करें।",noCurrent:"पहले कोई संदेश स्कैन करें। फिर मैं उसका जोखिम स्तर और चेतावनी संकेत बता सकता हूँ।",current:"यह संदेश अभी {level} जोखिम के रूप में चिह्नित है; स्कोर {score}/100 है। स्कैनर ने पहचाना: {reasons}। {safety}",currentClear:"यह संदेश अभी {level} जोखिम के रूप में चिह्नित है; स्कोर {score}/100 है। कोई ज्ञात चेतावनी संकेत नहीं मिला। सतर्क रहें। {safety}",currentSafety:"संदिग्ध लिंक न खोलें और OTP/PIN साझा न करें। बैंक के आधिकारिक माध्यम से जाँचें और जल्दबाज़ी न करें।"},
  ml:{otp:"OTP എന്നത് One-Time Password ആണ്; ഒരിക്കൽ ഉപയോഗിക്കുന്ന താൽക്കാലിക സ്ഥിരീകരണ കോഡാണിത്. ആരുമായും പങ്കിടരുത്. യഥാർത്ഥ ബാങ്കോ സഹായിയോ നിങ്ങളോട് OTP ചോദിക്കരുത്.",upiPin:"വേണ്ട. UPI PIN സ്വകാര്യമാണ്. ആരെങ്കിലും കോളിലൂടെയോ സന്ദേശത്തിലൂടെയോ ലിങ്കിലൂടെയോ ആവശ്യപ്പെട്ടാലും പങ്കിടുകയോ നൽകുകയോ ചെയ്യരുത്. പണം സ്വീകരിക്കാൻ UPI PIN ആവശ്യമില്ല.",lostMoney:"പണം നഷ്ടപ്പെട്ടാലോ തട്ടിപ്പിന് ഇരയായാലോ ബാങ്കുമായി ഉടൻ ബന്ധപ്പെടുകയും സൈബർ ക്രൈം ഹെൽപ്‌ലൈൻ 1930-ൽ വിളിക്കുകയും ചെയ്യുക. OTP അല്ലെങ്കിൽ UPI PIN ആരുമായും പങ്കിടരുത്.",scanner:"സന്ദേശ പരിശോധന തുറന്ന് SMS ചേർക്കുകയോ ടൈപ്പ് ചെയ്യുകയോ ചെയ്ത് സ്കാൻ ചെയ്യുക. പ്രാദേശിക നിയമ പരിശോധന സ്കോറും മുന്നറിയിപ്പുകളും സുരക്ഷാ ഉപദേശവും കാണിക്കും.",safetyGuide:"സുരക്ഷയ്ക്കായി OTP അല്ലെങ്കിൽ UPI PIN പങ്കിടരുത്; സംശയമുള്ള ലിങ്കുകൾ തുറക്കരുത്; ഔദ്യോഗിക ബാങ്ക് മാർഗ്ഗങ്ങളിലൂടെ പരിശോധിക്കുക; തിടുക്കപ്പെടരുത്. പണം നഷ്ടപ്പെട്ടാൽ ബാങ്കിനെയും 1930-നെയും ബന്ധപ്പെടുക.",noCurrent:"ആദ്യം ഒരു സന്ദേശം സ്കാൻ ചെയ്യുക. തുടർന്ന് അതിന്റെ അപകടനിലയും മുന്നറിയിപ്പുകളും വിശദീകരിക്കാം.",current:"ഈ സന്ദേശം ഇപ്പോൾ {level} അപകടമായി അടയാളപ്പെടുത്തിയിരിക്കുന്നു; സ്കോർ {score}/100. സ്കാനർ കണ്ടെത്തിയത്: {reasons}. {safety}",currentClear:"ഈ സന്ദേശം ഇപ്പോൾ {level} അപകടമാണ്; സ്കോർ {score}/100. അറിയപ്പെടുന്ന മുന്നറിയിപ്പുകളില്ല. ജാഗ്രത പാലിക്കുക. {safety}",currentSafety:"സംശയമുള്ള ലിങ്കുകൾ തുറക്കരുത്; OTP/PIN പങ്കിടരുത്. ഔദ്യോഗിക ബാങ്ക് മാർഗ്ഗത്തിലൂടെ പരിശോധിച്ച് തിടുക്കപ്പെടരുത്."}
};

window.NBV_VOICE.outputStatus = {
  en:"No installed voice matches the selected language. Your written answer is still available.",
  ta:"தேர்ந்தெடுத்த மொழிக்கான குரல் இல்லை. எழுதப்பட்ட பதிலைப் படிக்கலாம்.",
  te:"ఎంచుకున్న భాషకు వాయిస్ అందుబాటులో లేదు. రాతపూర్వక సమాధానం ఇక్కడే ఉంటుంది.",
  hi:"चुनी हुई भाषा के लिए आवाज़ उपलब्ध नहीं है। लिखा हुआ जवाब यहाँ पढ़ सकते हैं।",
  ml:"തിരഞ്ഞെടുത്ത ഭാഷയ്ക്ക് ശബ്ദം ലഭ്യമല്ല. എഴുതിയ ഉത്തരം ഇവിടെ ലഭ്യമാണ്."
};

window.NBV_VOICE.intents.en.upiPinWhat = [/\bwhat\s+(?:is|does)\s+(?:an?\s+)?upi\s*pin(?:\s+(?:mean|for))?\b|\bmeaning of (?:an?\s+)?upi\s*pin\b/i];
window.NBV_VOICE.intents.ta.upiPinWhat = [/upi\s*pin.{0,18}(?:என்றால் என்ன|என்ன)/iu];
window.NBV_VOICE.intents.te.upiPinWhat = [/upi\s*pin.{0,18}(?:అంటే ఏమిటి|ఏమిటి)/iu];
window.NBV_VOICE.intents.hi.upiPinWhat = [/upi\s*pin.{0,18}(?:क्या है|का मतलब)/iu];
window.NBV_VOICE.intents.ml.upiPinWhat = [/upi\s*pin.{0,18}(?:എന്താണ്|എന്നത് എന്താണ്)/iu];

window.NBV_VOICE.answers.en.upiPinWhat = "Your UPI PIN is the private code used to authorize UPI payments you send. Keep it secret; never share it. You do not need it to receive money.";
window.NBV_VOICE.answers.ta.upiPinWhat = "UPI PIN என்பது UPI வழியாக நீங்கள் பணம் அனுப்புவதை உறுதிப்படுத்தும் தனிப்பட்ட குறியீடு. அதை ரகசியமாக வைத்திருங்கள்; யாரிடமும் பகிராதீர்கள். பணம் பெற PIN தேவையில்லை.";
window.NBV_VOICE.answers.te.upiPinWhat = "UPI PIN అనేది UPI ద్వారా మీరు పంపే చెల్లింపులను ఆమోదించే వ్యక్తిగత కోడ్. దాన్ని రహస్యంగా ఉంచండి; ఎవరితోనూ పంచుకోవద్దు. డబ్బు స్వీకరించడానికి PIN అవసరం లేదు.";
window.NBV_VOICE.answers.hi.upiPinWhat = "UPI PIN वह निजी कोड है जिससे आप UPI के ज़रिए भेजे जाने वाले भुगतान की पुष्टि करते हैं। इसे गोपनीय रखें और किसी से साझा न करें। पैसे पाने के लिए PIN की ज़रूरत नहीं होती।";
window.NBV_VOICE.answers.ml.upiPinWhat = "UPI വഴി നിങ്ങൾ അയയ്ക്കുന്ന പണമിടപാട് അംഗീകരിക്കാൻ ഉപയോഗിക്കുന്ന സ്വകാര്യ കോഡാണ് UPI PIN. ഇത് രഹസ്യമായി സൂക്ഷിക്കുക; ആരുമായും പങ്കിടരുത്. പണം സ്വീകരിക്കാൻ PIN ആവശ്യമില്ല.";

window.NBV_VOICE.intents.ta.currentScan.push(/இந்த.{0,40}(?:message|செய்தி|sms).{0,30}(?:risk|ஆபத்து|பாதுகாப்பா|சந்தேக)/iu);
window.NBV_VOICE.intents.te.currentScan.push(/ఈ.{0,40}(?:message|సందేశం|sms).{0,30}(?:risk|ప్రమాదం|సురక్షితమా|అనుమాన)/iu);
window.NBV_VOICE.intents.hi.currentScan.push(/इस.{0,40}(?:message|संदेश|sms).{0,30}(?:risk|जोखिम|सुरक्षित|संदिग्ध)/iu);
window.NBV_VOICE.intents.ml.currentScan.push(/ഈ.{0,40}(?:message|സന്ദേശം|sms).{0,30}(?:risk|അപകടം|സുരക്ഷിതം|സംശയ)/iu);

window.NBV_VOICE.locale.tanglish = "ta-IN";
window.NBV_VOICE.ui.tanglish = {
  ...window.NBV_VOICE.ui.ta,
  youSaid:"Neenga sonnadhu:",
  listening:"Kekkiradhu… ippo pesunga.",
  stopped:"Kekkaradhu nindrathu.",
  unsupported:"Indha browser-la voice input support illai. Kelviyai type pannalaam.",
  recognitionError:"Voice input complete aagala. Kelviyai type pannalaam.",
  noSpeech:"Kural ketkala. Marubadi try pannunga illa type pannunga."
};

window.NBV_VOICE.intents.tanglish = {
  currentScan:[/\b(?:indha|intha)\b.{0,35}\b(?:message|sms|msg)\b.{0,25}\b(?:safe|risk|suspicious)\b/i,/\b(?:current|en)\b.{0,25}\b(?:scan|risk|result)\b.{0,25}\b(?:explain|enna|sollu)\b/i],
  lostMoney:[/\b(?:scam|fraud)\b.{0,35}\b(?:money|panam)\b.{0,25}\b(?:poiduchu|pochu|lost)\b/i,/\b(?:money|panam)\b.{0,20}\b(?:poiduchu|pochu|lost|stolen)\b/i,/\b(?:report|report panna)\b.{0,20}\b(?:fraud|scam)\b/i],
  upiPin:[/\bupi\s*pin\b/i],
  otp:[/\botp\b|\bone[ -]?time\s+password\b/i],
  scanner:[/\b(?:open|scan|check|verify)\b.{0,35}\b(?:scanner|message|sms)\b/i,/\b(?:message|sms)\b.{0,30}\b(?:scan|check|verify)\b/i],
  safetyGuide:[/\b(?:open|show)\b.{0,25}\b(?:safety\s+)?guide\b/i,/\bsafety\s+tips\b/i,/\bstay\s+safe\b.{0,30}\b(?:scam|fraud)\b/i],
  home:[/\b(?:go|open)\s+(?:to\s+)?home\b/i]
};
window.NBV_VOICE.intents.tanglish.upiPinWhat = [/\bwhat\s+(?:is|does)\s+(?:a\s+)?upi\s*pin\b/i,/\bupi\s*pin\b.{0,25}\b(?:enna|meaning)\b/i];
window.NBV_VOICE.answers.tanglish = {
  otp:"OTP-na One-Time Password. Idhu oru murai mattum use pannura temporary verification code. Yaar kitayum OTP share pannadheenga; genuine bank/support person kooda OTP kekka koodadhu.",
  upiPin:"Vendaam. UPI PIN private code. Call, message, link-la yaar kettaalum share pannadheenga. Money receive panna UPI PIN thevai illai.",
  upiPinWhat:"UPI PIN-na neenga UPI moolama anuppura payment-ai authorize panna use pannura private code. Idhai secret-a vechukkonga; yaar kitayum share pannadheenga. Money receive panna PIN thevai illai.",
  lostMoney:"Scam-la money poiduchuna, udane unga bank-ai contact pannunga; India cyber-crime helpline 1930-ku call pannunga. OTP illa UPI PIN-ai yaar kitayum share pannadheenga.",
  scanner:"Message Scanner open pannunga, SMS-ai paste illa type pannitu Scan message select pannunga. Existing local rule check score, warning signs, safety guidance kaattum.",
  safetyGuide:"Safety-ku OTP/UPI PIN share pannadheenga; suspicious link click pannadheenga; bank-oda official channel-la verify pannunga; urgent message-na rush aagatheenga. Money poiduchuna bank-aiyum 1930-aiyum contact pannunga.",
  noCurrent:"Mudhalil oru message scan pannunga. Appuram risk level-um warning signs-um explain panren.",
  current:"Indha message-ku existing scanner {level} risk, {score}/100 nu mark pannirukku. Scanner kandupidicha warning signs: {reasons}. {safety}",
  currentClear:"Indha message-ku existing scanner {level} risk, {score}/100 nu mark pannirukku. Therinja warning signs edhuvum kidaikkala; alert-a irunga. {safety}",
  currentSafety:"Suspicious link click pannadheenga; OTP/PIN share pannadheenga. Bank-oda official channel-la verify pannunga; urgent-nu sonnaalum rush aagatheenga.",
  unknown:"OTP, UPI PIN, scam-la money loss, suspicious message scan, illa safety tips pathi kelunga."
};

window.NBV_VOICE.outputStatus.tanglish = "Indha language-ku voice kidaikkala. Written answer-a padikkalaam.";
window.NBV_VOICE.aiStatus = {
  en:{thinking:"AI assistant is thinking…",answering:"Answering…",unavailable:"AI assistant unavailable — offline safety assistant is still available."},
  ta:{thinking:"AI உதவியாளர் யோசிக்கிறது…",answering:"பதில் அளிக்கிறது…",unavailable:"AI உதவியாளர் இப்போது கிடைக்கவில்லை — இணையமில்லா பாதுகாப்பு உதவியாளரைப் பயன்படுத்தலாம்."},
  te:{thinking:"AI సహాయకం ఆలోచిస్తోంది…",answering:"సమాధానం ఇస్తోంది…",unavailable:"AI సహాయకం అందుబాటులో లేదు — ఆఫ్‌లైన్ భద్రత సహాయకాన్ని ఉపయోగించవచ్చు."},
  hi:{thinking:"AI सहायक सोच रहा है…",answering:"जवाब दे रहा है…",unavailable:"AI सहायक अभी उपलब्ध नहीं है — ऑफ़लाइन सुरक्षा सहायक उपलब्ध है।"},
  ml:{thinking:"AI സഹായി ചിന്തിക്കുന്നു…",answering:"മറുപടി നൽകുന്നു…",unavailable:"AI സഹായി ഇപ്പോൾ ലഭ്യമല്ല — ഓഫ്‌ലൈൻ സുരക്ഷാ സഹായി ഉപയോഗിക്കാം."},
  tanglish:{thinking:"AI assistant yosikkudhu…",answering:"Badil solgiradhu…",unavailable:"AI assistant ippo available illa — offline safety assistant-a use pannalaam."}
};

window.NBV_VOICE.levelAdjective = {
  en:{LOW:"LOW",MEDIUM:"MEDIUM",HIGH:"HIGH"},
  ta:{LOW:"குறைந்த",MEDIUM:"நடுத்தர",HIGH:"அதிக"},
  te:{LOW:"తక్కువ",MEDIUM:"మధ్యస్థ",HIGH:"అధిక"},
  hi:{LOW:"कम",MEDIUM:"मध्यम",HIGH:"उच्च"},
  ml:{LOW:"കുറഞ്ഞ",MEDIUM:"ഇടത്തരം",HIGH:"ഉയർന്ന"},
  tanglish:{LOW:"LOW",MEDIUM:"MEDIUM",HIGH:"HIGH"}
};

window.NBV_VOICE.answers.ta.current = "இந்தச் செய்தி தற்போது {level} ஆபத்து எனக் குறிக்கப்பட்டுள்ளது; மதிப்பெண் {score}/100. கண்டறியப்பட்டவை: {reasons}. {safety}";
window.NBV_VOICE.answers.ta.currentClear = "இந்தச் செய்தி தற்போது {level} ஆபத்து; மதிப்பெண் {score}/100. அறியப்பட்ட எச்சரிக்கை அறிகுறிகள் இல்லை. விழிப்புடன் இருங்கள். {safety}";
window.NBV_VOICE.answers.te.current = "ఈ సందేశం ప్రస్తుతం {level} ప్రమాదంగా గుర్తించబడింది; స్కోరు {score}/100. స్కానర్ గుర్తించినవి: {reasons}. {safety}";
window.NBV_VOICE.answers.te.currentClear = "ఈ సందేశం ప్రస్తుతం {level} ప్రమాదం; స్కోరు {score}/100. తెలిసిన హెచ్చరికలు కనిపించలేదు. అప్రమత్తంగా ఉండండి. {safety}";
window.NBV_VOICE.answers.hi.current = "यह संदेश अभी {level} जोखिम के रूप में चिह्नित है; स्कोर {score}/100 है। स्कैनर ने पहचाना: {reasons}। {safety}";
window.NBV_VOICE.answers.hi.currentClear = "यह संदेश अभी {level} जोखिम के रूप में चिह्नित है; स्कोर {score}/100 है। कोई ज्ञात चेतावनी संकेत नहीं मिला। सतर्क रहें। {safety}";
window.NBV_VOICE.answers.ml.current = "ഈ സന്ദേശം ഇപ്പോൾ {level} അപകടമായി അടയാളപ്പെടുത്തിയിരിക്കുന്നു; സ്കോർ {score}/100. സ്കാനർ കണ്ടെത്തിയത്: {reasons}. {safety}";
window.NBV_VOICE.answers.ml.currentClear = "ഈ സന്ദേശം ഇപ്പോൾ {level} അപകടമാണ്; സ്കോർ {score}/100. അറിയപ്പെടുന്ന മുന്നറിയിപ്പുകളില്ല. ജാഗ്രത പാലിക്കുക. {safety}";
